import { ArtStyle } from './types';

// The image provided by the user, hosted externally.
const USER_IMAGE_URL = "https://i.ibb.co/L9qg7tJ/image.png";

export const ART_STYLES: ArtStyle[] = [
  { name: "Retro Futurism Neon", prompt: "Vibrant retro-futurism digital art, neon cyan and magenta glow, geometric shapes, chrome reflections, vaporwave-inspired atmosphere, 1980s sci-fi poster aesthetic.", image: USER_IMAGE_URL, filters: "saturate(200%) contrast(120%) hue-rotate(270deg)" },
  { name: "Gothic Charcoal Sketch", prompt: "Dark gothic ink and charcoal drawing, heavy shading, dramatic chiaroscuro, exaggerated features, moody and grim, reminiscent of medieval manuscripts and dark romanticism.", image: USER_IMAGE_URL, filters: "grayscale(100%) contrast(200%) brightness(80%)" },
  { name: "Cyberpunk Holographic", prompt: "High-tech cyberpunk digital painting, neon holographic overlays, glitch textures, sharp neon pink and electric blue palette, futuristic Tokyo street aesthetic.", image: USER_IMAGE_URL, filters: "saturate(250%) contrast(130%) hue-rotate(240deg)" },
  { name: "Minimalist Bauhaus", prompt: "Flat vector-based design, primary colors red, blue, yellow with black and white, clean geometry, straight lines, inspired by Bauhaus modernist posters.", image: USER_IMAGE_URL, filters: "saturate(200%) contrast(150%)" },
  { name: "Watercolor Dreamscape", prompt: "Soft watercolor painting, flowing washes, pastel tones, dreamy gradients, delicate blending of blues, pinks, and yellows, ethereal atmosphere.", image: USER_IMAGE_URL, filters: "saturate(120%) contrast(90%) opacity(80%)" },
  { name: "Expressionist Oil Portrait", prompt: "Thick impasto brushstrokes, expressive colors, emotional distortions, fiery reds and deep blues, Van Gogh-inspired textural intensity.", image: USER_IMAGE_URL, filters: "saturate(180%) contrast(130%)" },
  { name: "Surreal Collage", prompt: "Surrealist mixed-media collage, vintage photo cutouts, layered textures, bold abstract shapes, dreamlike juxtapositions, Salvador Dalí meets modern design.", image: USER_IMAGE_URL, filters: "contrast(140%) hue-rotate(45deg)" },
  { name: "Pop Art Comic", prompt: "Bright pop-art comic book style, halftone dots, bold primary colors, exaggerated outlines, Roy Lichtenstein-inspired visual punch.", image: USER_IMAGE_URL, filters: "saturate(300%) contrast(150%)" },
  { name: "Psychedelic 70s", prompt: "Swirling neon gradients, fractal-like shapes, rainbow spectrum palette, trippy kaleidoscopic symmetry, 1970s psychedelic poster aesthetic.", image: USER_IMAGE_URL, filters: "hue-rotate(180deg) saturate(250%) contrast(120%)" },
  { name: "Art Deco Luxury", prompt: "Geometric symmetry, metallic gold and black palette, elegant streamlined forms, 1920s art deco posters with cinematic grandeur.", image: USER_IMAGE_URL, filters: "contrast(120%) sepia(50%) saturate(150%)" },
  { name: "Vaporwave Aesthetic", prompt: "Soft pastel gradients, retro 90s computer graphics, glitch effects, pink and teal palette, nostalgic vaporwave aesthetic with surreal digital vibes.", image: USER_IMAGE_URL, filters: "hue-rotate(290deg) saturate(150%) contrast(90%)" },
  { name: "Ukiyo-e Japanese Woodblock", prompt: "Traditional Japanese ukiyo-e woodblock print style, flat planes of color, intricate linework, muted earthy tones, stylized waves and nature patterns.", image: USER_IMAGE_URL, filters: "sepia(30%) saturate(120%) contrast(110%)" },
  { name: "Brutalist Monochrome", prompt: "Harsh geometric minimalism, grayscale palette, concrete-like textures, bold blocky shapes, brutalist architectural illustration aesthetic.", image: USER_IMAGE_URL, filters: "grayscale(100%) contrast(180%)" },
  { name: "Steampunk Illustration", prompt: "Victorian steampunk aesthetic, brass and copper metallic tones, gears and machinery, detailed linework, sepia accents, retro-futuristic design.", image: USER_IMAGE_URL, filters: "sepia(80%) contrast(120%) saturate(80%)" },
  { name: "Fantasy Concept Art", prompt: "Epic fantasy digital painting, dramatic lighting, painterly brushwork, glowing magical elements, cinematic landscapes, inspired by game concept art.", image: USER_IMAGE_URL, filters: "contrast(110%) saturate(130%) brightness(110%)" },
  { name: "Memphis 80s", prompt: "Playful geometric shapes, bold colorful patterns, clashing bright colors, funky 1980s Memphis design aesthetic with pop graphics.", image: USER_IMAGE_URL, filters: "saturate(250%) contrast(130%)" },
  { name: "Noir Monochrome Photography", prompt: "High-contrast black and white noir photography, cinematic lighting, deep shadows, smoke-filled atmosphere, moody detective film aesthetic.", image: USER_IMAGE_URL, filters: "grayscale(100%) contrast(150%) brightness(90%)" },
  { name: "Abstract Geometric Vector", prompt: "Sharp vector geometry, vibrant color blocking, clean symmetry, overlapping transparent layers, Bauhaus and Kandinsky-inspired abstract minimalism.", image: USER_IMAGE_URL, filters: "saturate(200%) contrast(150%)" },
  { name: "Retro Poster Lithograph", prompt: "Vintage poster lithograph style, limited muted palette, grainy texture, bold block printing aesthetic, old advertising poster vibe.", image: USER_IMAGE_URL, filters: "sepia(60%) contrast(110%) brightness(95%)" },
  { name: "Ethereal Sci-Fi Pastel", prompt: "Futuristic digital painting with pastel neon tones, glowing clouds, surreal space-like backgrounds, dreamy sci-fi fantasy aesthetic with luminous highlights.", image: USER_IMAGE_URL, filters: "hue-rotate(200deg) saturate(120%) brightness(120%)" },
  { name: "Neo-Expressionist Graffiti", prompt: "Vivid neo-expressionist digital illustration, bold sketchy outlines, neon magenta, cyan and yellow, dripping paint textures, raw energy, abstract urban graffiti influence, expressive brush splatters, rebellious pop-art edge.", image: USER_IMAGE_URL, filters: "saturate(250%) contrast(140%) hue-rotate(300deg)" },
  { name: "Impressionistic Naive Painting", prompt: "Soft impressionistic oil painting style, loose brushstrokes with visible texture, warm earthy palette (ochre, olive green, terracotta, muted yellow), simplified shapes, Mediterranean dreamlike atmosphere, painterly naive aesthetic.", image: USER_IMAGE_URL, filters: "saturate(110%) contrast(100%) blur(0.5px)" },
  { name: "Whimsical Surreal Cartoon", prompt: "Whimsical surreal cartoon painting, elongated exaggerated characters, large expressive eyes, playful proportions, eerie yet childlike mood, bold contrast of teal and orange, smooth painterly gradients, Tim Burton-inspired quirky details.", image: USER_IMAGE_URL, filters: "saturate(160%) contrast(110%) hue-rotate(-20deg)" },
  { name: "Modern Digital Cel-Shaded", prompt: "Modern digital illustration, bold cel-shaded coloring, vibrant warm tones with pink and golden accents, smooth gradients with angular shadows, stylized semi-realistic features, clean vector-like edges, animation-inspired contemporary art.", image: USER_IMAGE_URL, filters: "saturate(180%) contrast(120%)" },
  { name: "Classical Ink Sketch", prompt: "Highly detailed black and white ink sketch, expressive linework, fine cross-hatching, strong chiaroscuro shading, classical portrait drawing, vintage etching aesthetic, traditional pen-and-ink illustration with dramatic lighting.", image: USER_IMAGE_URL, filters: "grayscale(100%) contrast(180%) brightness(110%) invert(10%)" },
  { name: "Duotone Urban Poster", prompt: "Modern graphic art with duotone palette (deep blue and vibrant yellow), expressive paint splatters and drips, high-contrast stylized forms, mix of realism and abstraction, poster-like design, energetic contemporary street-art influence.", image: USER_IMAGE_URL, filters: "contrast(200%) saturate(200%) hue-rotate(200deg) grayscale(50%)" },
  { name: "Abstract Neo-Expressionist Pop", prompt: "Abstract neo-expressionist painting, rough sketchy outlines, neon hot pink, orange, yellow accents, chaotic brushstrokes, dripping textures, graffiti-inspired raw composition, playful emotional atmosphere with modern street-art aesthetics.", image: USER_IMAGE_URL, filters: "saturate(300%) contrast(150%) hue-rotate(320deg)" },
  { name: "Cinematic Studio Portrait", prompt: "Professional studio portrait photography, sharp focus, clean composition, gradient backgrounds, dramatic key and rim lighting, cinematic cool-toned color grading, minimal aesthetic, confident and formal expressions.", image: USER_IMAGE_URL, filters: "contrast(110%) saturate(90%) sepia(20%)" },
  { name: "Hyper-Realistic Narrative Photography", prompt: "Ultra-realistic wide-angle studio photography, natural folds and textures, high-fashion streetwear editorial feel, vibrant teal, orange, and yellow paint splashes suspended mid-air, cinematic lighting with rim and accent highlights.", image: USER_IMAGE_URL, filters: "saturate(120%) contrast(105%)" },
  { name: "Surreal Nostalgic Realism", prompt: "Two versions of the same person (child and adult), captured in a surreal blurred backdrop, ultra-realistic skin textures, symbolic contrast of youth and maturity, dreamlike softened environments (rural fields, carnival, village moulid).", image: USER_IMAGE_URL, filters: "saturate(110%) contrast(100%) brightness(105%)" },
  { name: "Neo-Noir Graphic Novel", prompt: "Digital painting in a neo-noir graphic novel style, sharp angular brushstrokes, bold planes of light and shadow, chiaroscuro-inspired contrasts, muted grays with teal-blue undertones and crimson highlights, cinematic gritty mood, modern concept art meets comic book illustration.", image: USER_IMAGE_URL, filters: "grayscale(80%) contrast(160%) hue-rotate(180deg) saturate(150%)" }
];